### PR TITLE
Hide 'vscode-objectscript-output' language from selector (fixes #805)

### LINKED ISSUE #805: Language Mode quickpick includes an entry named `vscode-objectscript-output`
image

I think this is an internal language ID that we should hide from the selector. I plan to submit a PR.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #805

### CODE REVIEW

**Review by daimor — DISMISSED** [review]

**Comment by isc-bsaviano** [comment]
@daimor Is the CI failure caused by a known issue?

**Comment by daimor** [comment]
something new, but should not be a problem, atm

**Comment by isc-bsaviano** [comment]
It looks like an issue with the new `enabledApiProposals` property

**Comment by daimor** [comment]
And I can't reproduce it locally, yet

**Comment by gjsjohnmurray** [comment]
I think I have fixed the CI.

**Review by daimor — APPROVED** [review]

**Pull request merged**
