### PR TITLE
publisher and telemetry to intersystems-community

### PR DESCRIPTION
**Pull request by rajrsingh**

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
This relates to https://github.com/orgs/intersystems-community/teams/vs-code-objectscript-pmc/discussions/4, which references a strategy at https://github.com/microsoft/vscode/issues/59918#issuecomment-483412662 for migrating existing users to a renamed extension.

**Comment by daimor** [comment]
I’ve already sent a request to marketplace support about changing publisher, I would wait for response.

**Comment by rajrsingh** [comment]
> I’ve already sent a request to marketplace support about changing publisher, I would wait for response.

OK let's see if they answer by the end of the week.

**Review by daimor — APPROVED** [review]

**Comment by DumpySquare** [comment]
How do you open an issue with the vscode marketplace to accomplish this task?  I'm having trouble finding anything.

**Comment by daimor** [comment]
> How do you open an issue with the vscode marketplace to accomplish this task? I'm having trouble finding anything.

@DumpySquare 
sent email to: vsmarketplace@microsoft.com
--

**Pull request merged**
