### PR TITLE
fix #269 Server-side search of isfs folder using proposed API failed when using Server Manager connection

### LINKED ISSUE #269: Server-side search of isfs folder using proposed API failed when using Server Manager connection
Despite their package.json containing the expected `"enableProposedApi": true` setting, the FileSearchProvider and TextSearchProvider implementations don't seem to activate.

I suspect this is caused by the build procedure not adding vscode.proposed.d.ts

I will submit a PR.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #269

### CODE REVIEW

**Comment by daimor** [comment]
image
Now it doing the same twice

**Comment by gjsjohnmurray** [comment]
Yes I spotted that. Am investigating. Hence this is only a draft PR.

**Comment by gjsjohnmurray** [comment]
The original problem (proposed APIs not available) turned out to have been caused by me having forgotten that it's necessary to add the `--enable-proposed-api daimor.vscode-objectscript' argument when launching vscode-insider, otherwise our extension behaves as though its package.json specified `"enableProposedApi": false` even though the manually-installed VSIX (beta or snapshot) has this set to true.

Simpler than having to launch the Insiders executable from the command-line with this extra argument is to do this:
1. In Command Palette choose `Preferences: Configure Runtime Arguments`
2. In the argv.json file that opens, add this line:
`	"enable-proposed-api": ["daimor.vscode-objectscript"]`
3. Restart Insiders

Now you can use VS Code's Search (Ctrl/Cmd+Shift+F) to run a server-side search on your isfs folder(s), as long as the server supports v2 of the Atelier API.

**Comment by copperschnack** [comment]
> Now you can use VS Code's Search (Ctrl/Cmd+Shift+F) to run a server-side search on your isfs folder(s), as long as the server supports v2 of the Atelier API.

I cannot get the search to work in my environment: Querying for `classmethod` retrieves no results, where obviously it should.

* VS Code `1.50.0-insider (user setup)`
* Plugin `vscode-objectscript v0.9.3-beta.1`
* IRIS `2020.1` with `/api/atelier/v2` available and other server side content displayed correctly in VS Code workspace

image

**Comment by daimor** [comment]
it's maybe not obvious, but you cannot find all classmethods in any classes this way. It may find `$classmethod` in the code, or if you have it as text somewhere, but not just any classmethod. Could you try to compare it with Studio Search?

**Comment by daimor** [comment]
I would suggest trying to search for something else, not for keywords.

**Comment by copperschnack** [comment]
OK, thanks for the hint. I retried with a different search and added a comparision to Studio in a screenshot below. Our IRIS instance is an In-Place upgraded Caché-Instance. Just mentioning it, in case there might be caviots there.

image

**Comment by daimor** [comment]
Could you show if the Output in VSCode shows anything? It supposed to be exactly the same as in Studio.

**Comment by copperschnack** [comment]
There ist no output regarding searching. Compilation instead does appear like in Studio, see below:

`Compilation started on 09/14/2020 11:07:24 with qualifiers 'cuk', using up to 4 worker jobs`
`Compiling class tmp.SearchTest`
`Compiling routine tmp.SearchTest.1`
`Compilation finished successfully in 0.026s.`

**Comment by daimor** [comment]
Are you sure, that you started VSCode correctly?
Sorry, issue maybe just in renamed extension id, you have to use `intersystems-community.vscode-objectscript` instead of `daimor.vscode-objectscript`

**Comment by gjsjohnmurray** [comment]
I have updated the instructions above to reflect the new extension id.

Also, see https://github.com/intersystems-community/vscode-objectscript/issues/126#issuecomment-691966405 for a new indicator that you have set things up correctly. @copperschnack I suggest continuing this discussion on #126 rather than on this closed PR.

**Pull request merged**
