### PR TITLE
package updates

### PR DESCRIPTION
**Pull request by isc-rsingh**
This PR fixes #

### CODE REVIEW

**Comment by isc-rsingh** [comment]
@daimor can you look at these failures? I don't know why these linting issues should be stopping the checks.

**Comment by daimor** [comment]
There are some issues with dependencies, node-fetch requires newer version of typescript 4.* instead of current 3.*. And this cause to cascade of upgrades for related packages, such as linting and testing, I'll check and update the PR, later.

**Review by gjsjohnmurray — APPROVED** [review]
Looks OK but I didn't do any testing.

**Comment by isc-rsingh** [comment]
@daimor linting errors with prettier again.

**Comment by daimor** [comment]
I'll check, looks like some of the linting-related packages updated checks for linter.

**Comment by isc-rsingh** [comment]
Thanks @daimor. After @gjsjohnmurray reviews I will merge.

**Comment by isc-rsingh** [comment]
Or did we say the only meaningful way to test these changes is to use them?

**Comment by daimor** [comment]
Merge, get beta version and users will check it

**Review by isc-bsaviano — APPROVED** [review]

**Pull request merged**
