### PR TITLE
ci fix for enableProposedApi

### LINKED ISSUE #429: v1.0.2 failed to publish to Marketplace
See https://github.com/intersystems-community/vscode-objectscript/runs/1300135166?check_suite_focus=true

image

I don't understand why this happened when I created the v1.0.2 release but not with the previous v1.0.1

It seems that some step in the script didn't toggle `enableProposedApi` in settings.json when it should have.

@daimor please investigate.

### PR DESCRIPTION
**Pull request by daimor**
This PR fixes #429

### CODE REVIEW

**Review by gjsjohnmurray — APPROVED** [review]
Thanks for this. Once you have merged it will you be able to get CI to publish 1.0.2? If not then I can do a 1.0.3 release.

**Comment by daimor** [comment]
Yes

**Comment by daimor** [comment]
the trick did not happen, it just fails because the version already updated in package.json
so, better to create new release

**Comment by gjsjohnmurray** [comment]
The 1.0.3 release published to Marketplace but not to Open VSX Registry.

image

**Pull request merged**
