### PR TITLE
Fix `FileSystemProvider` mtime caching

### PR DESCRIPTION
**Pull request by isc-bsaviano**
This PR fixes `FileSystemProvider` mtime caching. Previously, the cache would get constantly overwritten so calls to `GET /doc` wouldn't include the `IF_NONE_MATCH` header, forcing the server to send the full contents of the file back every time. This fix corrects this problem so the proper mtime is sent with `GET /doc` requests.

### CODE REVIEW

**Review by gjsjohnmurray — APPROVED** [review]
Based on code-reading this looks OK to me. I haven't tested the dev VSIX though.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray @daimor There's something wrong with the CI. Compile fails because it can't find the `vscode` module. I'm not going to merge this until we get a CI run for this PR that succeeds

**Comment by daimor** [comment]
There is something wrong with downloading `vscode.proposed.d.ts`

**Comment by daimor** [comment]
https://github.com/microsoft/vscode/issues/136964

**Comment by gjsjohnmurray** [comment]
> 
> 
> [microsoft/vscode#136964](https://github.com/microsoft/vscode/issues/136964)

Correct. The CI needs to be revised to handle the relocation of vscode.d.ts and the breaking up of vscode.proposed.d.ts.

But I think the reason this is suddenly biting us is that the CI downloads these from main (actually, still using the old name 'master'). It should probably be using npx instead.

**Comment by daimor** [comment]
I'll take care of this change, and create a PR for it

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray We have a dev vsix for this now if you want to test it before I merge

**Comment by gjsjohnmurray** [comment]
A quick test of the dev vsix didn't find anything broken, so I'm happy for my approval to stand.

**Pull request merged**
