### PR TITLE
Support setting data breakpoints on subsequent debug sessions (fix #1251)

### LINKED ISSUE #1251: Data breakpoints (watchpoints) only settable on the first debug run
Discovered when investigating thread started by @isc-solon in https://github.com/intersystems-community/vscode-objectscript/issues/710#issuecomment-1761621231

I have a fix.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #1251

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@isc-solon @isc-rsingh please download the zip at https://github.com/intersystems-community/vscode-objectscript/suites/17213418630/artifacts/983708130 and extract the dev VSIX it contains, then install it and re-test setting data breakpoints.

**Comment by isc-solon** [comment]
Unfortunately, not fixed yet. I installed the vsix. Restarted VS Code. Added a breakpoint and clicked "Debug". A variable appeared in the VARIABLES section. When I right-clicked the variable, I saw "Break on value change" for the very first time! I didn't choose the option, however. I clicked "Step Over" button. Another variable appeared. But right-clicking doesn't offer the watchpoint option anymore for either variable. I added one of the variables to the WATCH section. Right-clicking the variable there also doesn't offer the watchpoint option.

**Comment by gjsjohnmurray** [comment]
Please try this one.

https://github.com/intersystems-community/vscode-objectscript/suites/17267930228/artifacts/986402685

Filename is unchanged but this one should work properly. Note though that "Break on Value Change" will only show up on unsubscripted variables on the Variables view.

**Comment by isc-solon** [comment]
The latest fix worked. Thanks! But...right-clicking on a variable in the WATCH section doesn't offer the watchpoint option. Is it possible to add that to this fix?

**Comment by gjsjohnmurray** [comment]
VS Code doesn't support setting data breakpoints from the Watch view, presumably because entries there are expressions.

**Review by isc-bsaviano — APPROVED** [review]

**Pull request merged**
