### PR TITLE
Add default file icons

### PR DESCRIPTION
**Pull request by isc-bsaviano**
https://github.com/microsoft/vscode/issues/140047 adds the ability to provide default file icons for contributed languages. This PR adds the InterSystems logo as the default file icon for all of our contributed languages (classes, routines, includes and CSP/CSR). Unfortunately, the Salesforce cloud will still be the file icon for `.cls` files because it comes from the default [Seti file icon theme](https://github.com/jesseweed/seti-ui). Once this PR gets approved we should consider opening a PR in that repo that uses this icon for `.mac`, `.int`,  `.inc`, `.csp` and `.csr` files so nobody else beats us to them.

EDIT: I've included some screenshots below.

This is the current behavior:
Screen Shot 2022-01-13 at 10 07 59 AM
This is with this PR using a dark theme:
Screen Shot 2022-01-13 at 1 20 54 PM
This is with this PR using a light theme:
Screen Shot 2022-01-13 at 1 21 08 PM

### CODE REVIEW

**Review by isc-rsingh — DISMISSED** [review]

**Review by daimor — APPROVED** [review]

**Comment by gjsjohnmurray** [comment]
Did you consider using the same icons as Studio, which would distinguish INC from MAC/IMT?

**Comment by gjsjohnmurray** [comment]
Also, won't this require 1.64?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray No, I didn't consider using those icons but I will look into it before merging this. Yes, this requires 1.64 to actually show the icons but when I tested on 1.63 everything worked the same as before so I think this is safe to merge before 1.64 is out.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I fired up Studio again to get a look at the icons and I don't think they're usable. I agree that it would be nice to have different icons for every file extension but since that's not possible in the `package.json` file I think this is good enough for now. If/when we decide to add icons to the Seti theme we can consider how to differentiate the different file types.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano each language contributed by the extension can specify a different icon.

At the moment we treat INTs and MACs as the same language. IMO this is a mistake, because it means I can write in my INTs code which is only valid in MACs (e.g. #-directives, embedded SQL etc) and only find out when I try to save/import them into a namespace.

To fix this I think we should add a new language `objectscript-int` and associate the .int extension with this rather than with `objectscript`. Then in this PR INTs and MACs can be given different icons.

I will open a separate issue for this, which I suggest should get priority over this PR.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano now that #865 has merged I suggest you merge master into your branch, update package.json to specify icons for the new `objectscript-int` language, and advance the PR out of Draft status. I'll be willing to approve it, even if we stick with the same generic svg for all of the languages at this stage.

**Pull request merged**
