### PR TITLE
Prevent overprompting for permission and account

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR leverages https://github.com/intersystems-community/intersystems-servermanager/pull/243

Requires Server Manager 3.8.0 in order to be effective, but shouldn't break when used with earlier version

### CODE REVIEW

**Review by isc-bsaviano — APPROVED** [review]
Thanks for doing this John. The code looks good. I will create a Language Server issue and get this fixed there tomorrow.

**Comment by a-boertien** [comment]
hi @gjsjohnmurray @isc-bsaviano 
I think there might be a bug with this...
I am being prompted on every file now to authenticate, and I receive this warning on authentication:

image

After selecting "Keep...", the same warning appears next time.
I have also tried signing out of all credentials in VSCode accounts menu.

Versions: server manager 3.8.0, objectscript 2.12.10, VSCode 1.95.2 (windows)

Should I raise a new issue?

**Comment by isc-bsaviano** [comment]
@a-boertien That's a bug in the Language Server 2.6.4 which is fixed in 2.6.5.

**Comment by a-boertien** [comment]
Thanks @isc-bsaviano - have just updated to 2.6.5 and it looks resolved!

**Comment by a-boertien** [comment]
hi @gjsjohnmurray @isc-bsaviano 
Just wanted to leave some positive feedback.
I was a long time sufferer of over prompting -- have not noticed any over the last week, so this is a welcome fix!

**Pull request merged**
