### PR TITLE
support isfs copy

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR addresses #854

### CODE REVIEW

**Review by daimor — DISMISSED** [review]

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I was able to use this to copy a single routine from the root of  one `isfs` folder to another but I wasn't able to copy a package containing a single class. Is that by design?

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I have pushed some fixes that should mean you can now copy packages.

**Comment by gjsjohnmurray** [comment]
I propose merging this despite the limitations identified by @DodgeDeBoulet in https://github.com/intersystems-community/vscode-objectscript/issues/854#issuecomment-1036318435

Separate issues can be opened for these if felt necessary. Resolving them doesn't look trivial because the Atelier APIs don't seem to offer the methods (e.g. deletion of package or CSP folder).

**Comment by gjsjohnmurray** [comment]
> I propose merging this despite the limitations identified by @DodgeDeBoulet in https://github.com/intersystems-community/vscode-objectscript/issues/854#issuecomment-1036318435

@isc-bsaviano @daimor if you are happy with my proposal please approve the PR

**Review by daimor — APPROVED** [review]

**Pull request merged**
