### PR TITLE
paths and images work

### PR DESCRIPTION
**Pull request by rajrsingh**
This PR fixes #

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
@rajrsingh I'm confused by this PR. You seem to have reverted the path fixes I did in PR #294.

With #294 I get this when using VS Code's preview of Installation.md

image

After I update from master that now contains your merge of this PR I get this:

image

Which was exactly what I'd previously fixed.

**Comment by daimor** [comment]
This files used to show here https://intersystems-community.github.io/vscode-objectscript/
And pictures there shows well

**Comment by gjsjohnmurray** [comment]
So presumably the way that site places the pages relative to the images is different from how they're laid out in the repo tree. This is unfortunate, as it means doc links and images can't be previewed correctly direct in VS Code. ☹️

**Comment by rajrsingh** [comment]
I should have made it more clear how to test this. To preview properly one must follow this guidance:
https://docs.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

**Pull request merged**
