### PR TITLE
fix #337 handle Unicode chars in identifiers

### LINKED ISSUE #337: Support additional characters in classnames
The classname `tmp.BigBäng` is supported in Studio. In VS Code, I get the following error when I save my changes, see Screenshot.

`ERROR #5001: Couldn't get text for tmp.BigB.cls`
`ERROR #16000: Line: 'Line: 0 Offset: 0 ERROR #5351: Class 'tmp.BigB' does not exist.' Offset: '%2'`

image

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #337 and also corrects TextMate handling of identifiers that contain Unicode characters.

### CODE REVIEW

**Review by daimor — APPROVED** [review]

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano please note how this PR updated a regex in src/utils/index.ts to cater for Unicode characters in the classname identifier  at the top of a file. I spotted a similar regex at https://github.com/intersystems/language-server/blob/e39258b1df0c23bf47c63a76f9ecc96b96336f18/server/src/server.ts#L2443

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I was actually looking at this this morning. I tried to replace the [a-z0-9] in my regex with [\\p{Alnum}] but that wasn't working for me. Testing the new regex in a node terminal showed that class definition lines that were syntactically correct failed the regex check.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano the `{Alnum}` and `{Alpha}` syntax is what the TextMate handler needs in its regexes. Look at https://github.com/gjsjohnmurray/vscode-objectscript/blob/b7467eb0889736a896d5441d12138647a1de5332/src/utils/index.ts#L90 for how Node needs it.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Ok. {L} includes numerical characters as well?

**Comment by gjsjohnmurray** [comment]
> @gjsjohnmurray Ok. {L} includes numerical characters as well?

No, that's what the `\d` is for.

**Pull request merged**
