### PR TITLE
Custom background color for Generated

### PR DESCRIPTION
**Pull request by daimor**
The proposed realization for the discussed topic #987

### CODE REVIEW

**Review by gjsjohnmurray — CHANGES_REQUESTED** [review]
This is ugly because it affects other visible editors, not just the one that contains generated code.

There is a better way using [TextEditorDecorationType](https://code.visualstudio.com/api/references/vscode-api#TextEditorDecorationType)

```ts
	const readonlyDocumentDecorationType = vscode.window.createTextEditorDecorationType({
		isWholeLine: true,
		backgroundColor: new vscode.ThemeColor('objectscript.generatedCodeBackground')
	});
```

Then use [TextEditor](https://code.visualstudio.com/api/references/vscode-api#TextEditor)'s setDecorations method for every line of an editor containing generated code.

For best results use some transparency on the colors you choose.

**Comment by isc-bsaviano** [comment]
@daimor @gjsjohnmurray Is it possible to add an extra icon to the editor tab instead of changing the background color? That would be less intrusive IMO and would remove the need to coordinate colors with themes and possibly introduce accessibility concerns.

**Comment by gjsjohnmurray** [comment]
> Is it possible to add an extra icon to the editor tab

We could experiment with [FileDecorationProvider](https://code.visualstudio.com/api/references/vscode-api#FileDecorationProvider). Perhaps use 'G' as the `badge` property of the `FileDecoration` and 'Generated' as the `tooltip`. Or even add info to the tooltip to say what it is generated from.

**Comment by isc-bsaviano** [comment]
Closing in favor of #1035

**Pull request closed without merging**
