### PR TITLE
Add command for opening InterSystems documents

### LINKED ISSUE #1379: Server-Side editing Open items as in Studio
Using Studio is possible to open ANY "file" (class, routine, include, csp, csr, etc.) that is "available" (local or via mapping) in the current namespace.
I don't think this is possible using VS Code, or at least, if possible, it's not as easy and simple.

For example, if I need to open a % class and I've copied the classname in clipboard from documentation (or I type it in), in Studio I just press ctrl-O, ctrl-V (or type the name) and press enter and the class is opened.
This is possible not only for classes but for any other "file", for example if I want to open %occInclude.inc (a very popular include file) I can easily do it in Studio.
In fact, in Studio using the File Open dialog I can select the file type I want to open and choose/browse from a list, this is also very useful if you don't remember the exact spelling/case of an item and provide autocompletion as I type as well.
Another example, in Studio you can open the class and/or the routine(s) generated for an SQL statement, you get the class or routine name from Management Portal and in Studio you just press ctrl-O and paste the class or routine name and you have it opened.

Even for items that are part of the current virtual folder structure I did not find an easy way to open a class without browsing the virtual folder structure. If I have copied in clipboard a classname, say "HS.FHIR.DTL.SDA3.vR4.Address.Address.cls", how can I open it immediately? Browsing the folder structure is a pain!
I've tried using [the new "Quick Open" feature](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_quick-open) but that feature works only for "file" name, in my example the file name is "Address.cls" and I get a list of more then 20 files to choose from, many with similar packege name/path! Quick is an opinion.....

As a side note, to me the fact that for the class HS.FHIR.DTL.SDA3.vR4.Address.Address.cls the file name is actually Address.cls is...well...debatable, I consider the package as integral part of a classname. But maybe that my opinion.

IMHO in VS Code you should be able to open the same "items" I used to open in Studio. Hopefully as easily as in Studio.

I'm using v2.12.6-beta.1 with proposed API enabled.

### PR DESCRIPTION
**Pull request by isc-bsaviano**
This PR fixes #1379. The new `Open InterSystems Document...` command can be opened from the command palette and it provides a UI for browsing all files in the connected server-namespace. The user can either pick an item in the list, or type text into the filter box and press "Enter" to submit that. The UI should function very similarity to the built-in simple file dialog. I would like to assign a keybinding to this command, but I couldn't find a good one so I'm open to suggestions. 

output

### CODE REVIEW

**Review by isc-rsingh — DISMISSED** [review]

**Comment by isc-bsaviano** [comment]
@isc-rsingh @gjsjohnmurray How do you feel about using a chord ask the keybinding for this? `Ctrl+K Alt+O` (`Cmd+K Alt+O` on Mac) is available. We could also overload `Ctrl+K Shift+O` (`Cmd+K Shift+O` on Mac), which is only use din the diff editor. This is the best that I could come up with ending with `O`.

**Comment by isc-rsingh** [comment]
How about `Ctrl+K Ctrl+O` (Mac: `Cmd+K Cmd+O`) which seems easy to type and available.

**Comment by isc-bsaviano** [comment]
That's taken on Windows

**Comment by isc-rsingh** [comment]
Ugh. Now I see the semantics are different on Windows and Mac. On Mac, Cmd+O does both the open file and open folder semantics. While on Windows there are 2 separate keybindings, Ctrl+O for open file and the chord `Ctrl+K Ctrl+O` for open folder. I think the best available option is the chord `Ctrl+K Ctrl+Shift+O` and Mac `Cmd+K Cmd+Shift+O`?

**Comment by isc-bsaviano** [comment]
I think `Ctrl+K Alt+O` is better because it's fewer keys but I'm not sure any of these are natural/easy to use.

**Comment by isc-rsingh** [comment]
My suggestion was based on the convenience of not lifting the finger off of `Ctrl` (or `Cmd`) when typing the 2nd part of the chord, which is why I preferred it over a chord that changes all the finger positions, but its not a huge difference.

**Comment by isc-bsaviano** [comment]
That's a good point. Let's see what John thinks.

**Comment by gjsjohnmurray** [comment]
Adding keybindings to new versions of existing extensions brings the risk that some current users will experience problems because the combo we choose clashes with another extension or a keybinding they set up.

I'd be inclined not to set one.

**Comment by isc-bsaviano** [comment]
I'm fine with not setting one

**Comment by isc-bsaviano** [comment]
If you're both happy with this I'll merge it

**Comment by gjsjohnmurray** [comment]
I shan't have time to review / try this before tomorrow, so go ahead if you want.

**Comment by isc-bsaviano** [comment]
No problem John, I'll wait for you review

**Comment by gjsjohnmurray** [comment]
How about adding the command to the Explorer view title menu, perhaps with `go-to-file` as its icon?

**Comment by gjsjohnmurray** [comment]
Mapped .inc documents are not being hidden. To reproduce this, be connected to a namespace such as USER, set toggles to show system documents and to hide mapped ones. Observe that some %-packages still get listed. Drill into one and discover that you are being offered .inc documents despite them being mapped here from another database.

**Comment by gjsjohnmurray** [comment]
It would be nice if the three toggle buttons remembered their state between invocations of the selector, at least for the duration of my session, and perhaps persist per workspace.

It would also be nice if I could see the state of each. AFAIK the only way of doing this at the moment might be to create 6 of our own icons, 3 to represent "on" and 3 "off", then manipulate the `buttons` array. Perhaps the "on" icons would have a solid outline.

Alternatively I could have a go at a PR for https://github.com/microsoft/vscode/issues/185356, or better still my suggestion at https://github.com/microsoft/vscode/issues/221397#issuecomment-2225357158 gets accepted.

**Comment by isc-bsaviano** [comment]
> How about adding the command to the Explorer view title menu, perhaps with `go-to-file` as its icon?

You mean the default File Explorer, right? I will see if I can add the command there.

> Mapped .inc documents are not being hidden. To reproduce this, be connected to a namespace such as USER, set toggles to show system documents and to hide mapped ones. Observe that some %-packages still get listed. Drill into one and discover that you are being offered .inc documents despite them being mapped here from another database.

This sounds like a bug in the `%Library.RoutineMgr_StudioOpenDialog()` query. Please report it to the WRC.

> It would be nice if the three toggle buttons remembered their state between invocations of the selector, at least for the duration of my session, and perhaps persist per workspace.
> 
> It would also be nice if I could see the state of each. AFAIK the only way of doing this at the moment might be to create 6 of our own icons, 3 to represent "on" and 3 "off", then manipulate the `buttons` array. Perhaps the "on" icons would have a solid outline.
> 
> Alternatively I could have a go at a PR for [microsoft/vscode#185356](https://github.com/microsoft/vscode/issues/185356), or better still my suggestion at [microsoft/vscode#221397 (comment)](https://github.com/microsoft/vscode/issues/221397#issuecomment-2225357158) gets accepted.

I completely agree; this is why I opened that issue a while ago. I think your suggestion or the colored buttons would both be good solutions to this problem.

**Comment by gjsjohnmurray** [comment]
> You mean the default File Explorer, right? I will see if I can add the command there.

Yes.

Another bit of feedback:

image

Could the title be reworded "Open a document in ..."?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I have that clumsy language to allow for the API caller to change the suffix but since we have no other callers now I can change that

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I wasn't able to add the command inline using an icon, but it does appear in the `...` menu next to the other icons.

**Comment by gjsjohnmurray** [comment]
Did you try adding `"group": "navigation"` to the new entry?

**Comment by isc-bsaviano** [comment]
That worked! I tried `"group": "inline"` originally, which didn't work.

**Comment by gjsjohnmurray** [comment]
> This sounds like a bug in the `%Library.RoutineMgr_StudioOpenDialog()` query. Please report it to the WRC.

Logged in WRC as 989244

**Comment by gjsjohnmurray** [comment]
On a multiroot isfs workspace could the "Select workspace folder" selector default to the folder of the current active document rather thann the first folder?

**Comment by isc-bsaviano** [comment]
The `showWorkspaceFolderPick()` doesn't allow you to set a default value. I suppose we could create a custom `QuickPick` with the default set, but that seems a little overkill to me.

**Comment by gjsjohnmurray** [comment]
> I suppose we could create a custom QuickPick

I agree it's not worth the effort of doing that.

**Comment by isc-bsaviano** [comment]
Thanks for all the feedback. I think this is ready to go. If/when we get toggle buttons or colored buttons for `QuickPick` I will add that to all places in ur extension that would benefit, including this command.

**Comment by gjsjohnmurray** [comment]
> Logged in WRC as 989244

Confirmed by WRC, and Jira DP-433169 opened.

**Review by gjsjohnmurray — APPROVED** [review]
Great new feature!

**Comment by gjsjohnmurray** [comment]
> > Logged in WRC as 989244
> 
> Confirmed by WRC, and Jira DP-433169 opened.

Fixed by MAK5922 (Do not display routines from IRISLIB/IRISSYS when 'mapped=0' parameter for StudioOpenDialog query) which may appear in 2024.3

**Pull request merged**
