### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by isc-bsaviano**

### CODE REVIEW

**Comment by isc-bsaviano** [comment]
Do we really need to build on all three platforms? Action `coactions/setup-xvfb@v1` hasn't been updated to Node 20, but xvfb is already installed in the latest Ubuntu runners. Also, The Windows build started failing and updating the actions didn't help.

**Comment by isc-rsingh** [comment]
I haven't looked into what these checks do, but running successfully on Mac and Windows is key -- and marginally Ubuntu (as a proxy for all Linuxes). Are you saying running these checks on all these platforms aren't helping us ensure that?

**Comment by isc-bsaviano** [comment]
Yes, exactly. This extension is pure JavaScript and therefore is platform independent. Testing on one OS (Ubuntu) is good enough.

**Comment by gjsjohnmurray** [comment]
@daimor ought to know, but I guess one reason for running the CI on the different platforms is so that the tests happen on them. But seeing as no actual tests have been written yet we're unlikely to be losing anything by reducing the CI to a single platform.

**Comment by isc-bsaviano** [comment]
Yeah, that's probably the reason Dmitry implemented the CI the way he did.

**Comment by isc-bsaviano** [comment]
I updated the build CI to only run on Ubuntu. It succeeded, and there are no more deprecation warnings.

**Review by gjsjohnmurray — APPROVED** [review]

**Pull request merged**
