### PR TITLE
Implement async server-side search

### PR DESCRIPTION
**Pull request by isc-bsaviano**
This PR adds support for async server-side searching, which was added in Atelier API v6. This will help avoid timeout issues and improve UX by showing results continuously instead of all at once after the entire search has completed.

### CODE REVIEW

**Comment by isc-bsaviano** [comment]
Promoting from draft due to the release of the first [2023.1 developer preview](https://community.intersystems.com/post/starting-developer-preview-1-intersystems-iris-iris-health-healthshare-health-connect-20231), which contains Atelier API v6.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray @isc-rsingh Have either of you had the chance to try this yet? I would like to get this merged soon

**Comment by isc-rsingh** [comment]
will try it out before end of week

**Review by gjsjohnmurray — APPROVED** [review]
Cursory test was successful with IRIS for Windows (x86-64) 2023.1 (Build 196U) Mon Feb 13 2023 22:33:29 EST

First results displayed a lot faster than when the same search was done on IRIS for Windows (x86-64) 2022.1 (Build 209U) Tue May 31 2022 12:16:40 EDT

👍

**Pull request merged**
