### PR TITLE
Add snippets for Projection and XData

### LINKED ISSUE #480: Snippets for XData and Projection class members
XData and Projection are also class members, but there are no snippets for them.

### PR DESCRIPTION
**Pull request by isc-kiyer**
This PR fixes #480

### CODE REVIEW

**Review by daimor — CHANGES_REQUESTED** [review]
$0 needed in XData

**Comment by isc-kiyer** [comment]
> $0 needed in XData

@daimor I have pushed the new change here but the PR hasn't updated yet: https://github.com/intersystems-community/vscode-objectscript/compare/master...isc-kiyer:fix-480?expand=1
Is there something I need to do to force it to update?

**Comment by daimor** [comment]
No special actions needed, just add new commit with that change to the same branch, and push it, to the same remote

**Comment by isc-kiyer** [comment]
@daimor I did that but the PR still did not update. Will close this one and request a new PR

**Pull request closed without merging**
