### PR TITLE
Add watchpoint support

### LINKED ISSUE #697: Support watchpoints in debugger
The command line and Studio debuggers support watchpoints. I'm posting this issue to see if there are any plans to add this as an enhancement for VS Code - ObjectScript.

### PR DESCRIPTION
**Pull request by isc-bsaviano**
This PR fixes #697

### CODE REVIEW

**Review by gjsjohnmurray — APPROVED** [review]

**Comment by isc-solon** [comment]
I remember this being completed, but I don't see a way in VS Code to actually declare a watchpoint, and this capability is not documented. Adding @rajrsingh

**Comment by isc-solon** [comment]
Thanks, John. I didn't think to check the code doc itself. Very clear. But...my context menu only shows "Add to Watch" and none of the "Break on" options.

**Comment by gjsjohnmurray** [comment]
Here's what I get:

image

And after I select it a new entry appears in the BREAKPOINTS section:

image

Then after I continue (F5) here's where execution next stops:

image

**Comment by isc-solon** [comment]
Fascinating! Whether I'm in a class method or a .Mac routine,  and whether or not I right-click on the variable in the Variables section or the Watch section, I don't see "Break On Value Change".

I'm on the latest versions of VS Code and the extensions, and I'm running v2023.2 of IRIS for Health. I don't have that "proposed APIs" thing enabled.

**Comment by isc-rsingh** [comment]
I don't have a "Break on value change" menu item either

image

**Comment by isc-solon** [comment]
Do "proposed APIs" ever become "standard APIs?"

**Comment by isc-rsingh** [comment]
We're hoping so...

**Comment by gjsjohnmurray** [comment]
What you're seeing is unrelated to proposed API. Please see https://github.com/intersystems-community/vscode-objectscript/pull/1252#issuecomment-1762246234

**Pull request merged**
