### PR TITLE
Use Server Manager's View Container

### PR DESCRIPTION
**Pull request by isc-bsaviano**
The goal of this PR and its dependency is to group all three InterSystems views (Explorer, Projects, Servers) under a single "InterSystems" view container. The end result for the user will be a single view container using the ISC logo containing all three views, instead of the Servers view being under the "InterSystems Tools" view container (toolbox.

Requires https://github.com/intersystems-community/intersystems-servermanager/pull/216

### CODE REVIEW

**Comment by gjsjohnmurray** [comment]
Today I have installed this dev VSIX and the Server Manager one (https://github.com/intersystems-community/intersystems-servermanager/pull/216), so they'll start getting some usage here.

Perhaps we should release this as 2.12.0 in recognition of its new dependency on Server Manager, which we are also intending to increment the minor version of (to 3.6.0)

**Comment by isc-bsaviano** [comment]
Thanks for trying this John! I didn't bump the minor version here because I did it in #1269 and I figured that both of these PRs would be in a hypothetical 2.12.0.

**Comment by isc-rsingh** [comment]
@isc-bsaviano with the merged views we lose the "ObjectScript" heading on the container, so I suggest changing the "Explorer" panel to "ObjectScript Explorer". 

image

**Comment by isc-bsaviano** [comment]
@isc-rsingh I don't mind calling it the "InterSystems Explorer" (the view container's name plus the view's name), which is what will be shown if the view is moved from the default view container. I've already alerted Shawn that the docs will need some changes to accommodate this pull request so I don't see this minor name change as a problem.

**Review by isc-rsingh — APPROVED** [review]

**Review by gjsjohnmurray — APPROVED** [review]

**Pull request merged**
